name: Megami Ibunroku Persona (JP1) - open
sha1: b5a2b10cd7ed4ec2d01fddef304191a44c37769f

options:
  platform: psx
  basename: open
  base_path: ../..
  target_path: rom/JP1/EXE/OPEN.EXE
  asm_path: asm/JP1/open
  src_path: src/open
  build_path: build/JP1
  o_path: lib
  ld_script_path: linkers/JP1/open.ld
  symbol_addrs_path: configs/JP1/sym.open.txt
  undefined_syms_auto_path: linkers/JP1/undefined_syms_auto.open.txt
  undefined_funcs_auto_path: linkers/JP1/undefined_funcs_auto.open.txt
  compiler: GCC
  find_file_boundaries: True
  create_asm_dependencies: True
  disassemble_all: False
  hasm_in_src_path: True
  o_as_suffix: False
  use_legacy_include_asm: False
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False
  section_order: [".text", ".data", ".rodata", ".bss"]
  subalign: 4
  ld_align_section_vram_end: True
  ld_align_segment_vram_end: True
  ld_bss_is_noload: False
  symbol_name_format: $VRAM
  string_encoding: SHIFT-JIS
  data_string_encoding: SHIFT-JIS
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
  gp_value: 0x800B4090

segments:
  - name: header
    type: header
    start: 0x0
    vram: 0x80080000

  - name: open
    type: code
    start: 0x800
    vram: 0x80080000
    subsegments:
      - [0x800, asm, open]
      - [0x9C30, c, str]
      - [0x9CE4, asm, open_1]
      # Psy-Q from the library entry down; not ours to decompile.
      - [0xA038, asm, psyq/libs]

  - [0x35000]
