"""Turn Ghidra's exported code/data map into splat symbol_addrs files.

Interleaved data inside .text cannot be expressed as a splat `data` subsegment -
splat would move it into .data after .text and change the byte order. Instead we
emit explicit symbols with `type:`/`size:` so spimdisasm renders each region
inline, in place, and the section round-trips byte-for-byte.

Ghidra's function boundaries are also better than spimdisasm's heuristics
(spimdisasm merged 0x800119DC and 0x80011AB0 into one 412-byte blob; Ghidra
splits them correctly), so functions are pinned here too.
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GAME = "p1-jp"
GHIDRA = os.path.join(ROOT, "config", GAME, "ghidra")

# target -> (ghidra json, address space, vram base, file offset of that vram)
TARGETS = {
    "main":   ("SLPS_005_00.json", "ram",        0x80010000, 0x800),
    "atlus":  ("ATLUS_EXE.json",   "ram",        0x80080000, 0x800),
    "open":   ("OPEN_EXE.json",    "ram",        0x80080000, 0x800),
    "movie":  ("MOVIE_EXE.json",   "ram",        0x80080000, 0x800),
    "end":    ("END_EXE.json",     "ram",        0x80080000, 0x800),
    "dng":    ("SLPS_005_00.json", "OVL_DNG",    0x800643A0, 0x0),
    "btlp":   ("SLPS_005_00.json", "OVL_BTLP",   0x800643A0, 0x0),
    "s2d":    ("SLPS_005_00.json", "OVL_S2D",    0x800643A0, 0x0),
    "adv":    ("SLPS_005_00.json", "OVL_ADV",    0x800643A0, 0x0),
    "casino": ("SLPS_005_00.json", "OVL_CASINO", 0x800643A0, 0x0),
    "name":   ("SLPS_005_00.json", "OVL_NAME",   0x800643A0, 0x0),
}


def merge(ranges):
    """Merge overlapping/adjacent [lo, hi] inclusive ranges."""
    if not ranges:
        return []
    ranges = sorted(ranges)
    out = [list(ranges[0])]
    for lo, hi in ranges[1:]:
        if lo <= out[-1][1] + 1:
            out[-1][1] = max(out[-1][1], hi)
        else:
            out.append([lo, hi])
    return out


def gen(target):
    jf, space, vram_base, _rom = TARGETS[target]
    is_overlay = _rom == 0x0
    data = json.load(open(os.path.join(GHIDRA, jf)))
    sp = data["spaces"][space]
    blk = sp["blocks"][0]
    lo, hi = blk["start"], blk["end"]
    if is_overlay:
        lo += 4          # the id dword is owned by the config's data subsegment

    # Group pieces by owning entry point; a handful of functions are
    # non-contiguous, so span entry..max across all of their pieces.
    # MIPS instructions are 4-byte aligned. Ghidra occasionally reports a
    # degenerate 1-byte body (e.g. func_800119CC), which would otherwise emit a
    # misaligned data run and make spimdisasm bail on everything after it.
    by_entry = {}
    for entry, f_lo, f_hi in sp["funcs"]:
        if f_lo < lo or f_hi > hi:
            continue
        f_lo &= ~3
        f_hi |= 3
        cur = by_entry.get(entry)
        by_entry[entry] = (min(cur[0], f_lo), max(cur[1], f_hi)) if cur else (f_lo, f_hi)
    # A real MIPS function is at least `jr $ra` + delay slot. Ghidra sometimes
    # leaves 4-byte stubs; keeping them makes spimdisasm demote the *next* real
    # function to a plain label, so let those bytes fall into the data runs.
    funcs = sorted((v[0], v[1], k) for k, v in by_entry.items()
                   if v[1] - v[0] + 1 >= 8)
    dropped = len(by_entry) - len(funcs)

    # Ghidra excludes trailing alignment padding from a function body, leaving
    # 4..16 byte islands between functions. Emitting those as data runs makes
    # spimdisasm demote every following function to a plain label, so absorb
    # them back into the preceding function instead.
    PAD = 16
    absorbed = 0
    for i in range(len(funcs) - 1):
        f_lo, f_hi, entry = funcs[i]
        nxt = funcs[i + 1][0]
        gap = nxt - (f_hi + 1)
        if 0 < gap <= PAD:
            funcs[i] = (f_lo, nxt - 1, entry)
            absorbed += 1
    covered = merge([[a, b] for a, b, _ in funcs])

    lines = [
        f"// Generated by tools/gen_symbols.py from Ghidra analysis.",
        f"// {target}: space={space} vram=0x{lo:08X}-0x{hi:08X}",
        "",
    ]

    # Functions, with exact sizes so spimdisasm cannot merge neighbours.
    for f_lo, f_hi, entry in funcs:
        size = f_hi - f_lo + 1
        lines.append(f"func_{entry:08X} = 0x{entry:08X}; // type:func size:0x{size:X}")

    # Everything in the block not covered by a function is data, emitted inline
    # as word runs so the original byte order is preserved exactly.
    # A tiny data island *before* the first function demotes everything after
    # it too (NAME.BIN: the 4-byte overlay-id dword sits at base+0, first
    # function at base+4). Fold it into the first function's range.
    # NOTE: do not fold a leading data island into the first function - an
    # overlay's id dword (e.g. NAME.BIN's 0x00000009) is not a valid MIPS
    # instruction and will not assemble. The splat config carves it out as its
    # own data subsegment instead.
    lead = 0

    lines.append("")
    gaps, cur = [], lo
    for f_lo, f_hi in covered:
        if f_lo > cur:
            gaps.append((cur, f_lo - 1))
        cur = max(cur, f_hi + 1)
    if cur <= hi:
        gaps.append((cur, hi))

    # Addresses the code references but which fall inside a data run would
    # otherwise disassemble as  D_<runstart>+0xNNN . Split the run at each so
    # every reference gets its own symbol, which is what C sources declare.
    refs = set()
    for fname in (f"{target}.undefined_extra.txt", f"{target}.refs.txt"):
        path_r = os.path.join(ROOT, "config", GAME, fname)
        if not os.path.exists(path_r):
            continue
        for line in open(path_r):
            m = re.search(r"=\s*0x([0-9A-Fa-f]{8})\s*;", line)
            if m:
                a = int(m.group(1), 16)
                if lo <= a <= hi and a % 4 == 0:
                    refs.add(a)

    nsplit = 0
    for g_lo, g_hi in gaps:
        cuts = sorted(a for a in refs if g_lo < a <= g_hi)
        start = g_lo
        for c in cuts:
            lines.append(f"D_{start:08X} = 0x{start:08X}; // type:u32 size:0x{c - start:X}")
            nsplit += 1
            start = c
        lines.append(f"D_{start:08X} = 0x{start:08X}; // type:u32 size:0x{g_hi - start + 1:X}")

    for a, b in gaps:
        assert a % 4 == 0 and (b + 1) % 4 == 0, f"{target}: misaligned gap {a:08X}-{b:08X}"
    for a, b, _ in funcs:
        assert a % 4 == 0 and (b + 1) % 4 == 0, f"{target}: misaligned func {a:08X}-{b:08X}"

    out = os.path.join(ROOT, "config", GAME, f"{target}.symbols.txt")
    with open(out, "w", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")

    code = sum(b - a + 1 for a, b in covered)
    dat = sum(b - a + 1 for a, b in gaps)
    print(f"  {target:8} {len(funcs):5} funcs ({code:7} B code)  "
          f"{len(gaps):5} data runs ({dat:7} B data)  "
          f"{100.0*code/(code+dat):5.1f}% code"
          + (f"  -{dropped} stubs" if dropped else "")
          + (f"  +{absorbed} pad" if absorbed else "")
          + (f"  +{lead}B lead" if lead else "")
          + (f"  +{nsplit} ref splits" if nsplit else ""))


if __name__ == "__main__":
    names = sys.argv[1:] or list(TARGETS)
    print("target    functions            data                       ratio")
    for t in names:
        gen(t)
