"""Emit a linker fragment mapping real symbol names to their in-binary addresses.

The Psy-Q SDK code is already present in every target binary, and Ghidra's PsyQ
signature analyser has named it (CdControlB, CdRead, GsInitGraph, ...). Feeding
those names to the linker means C sources can call the SDK by its real names,
against the vendored Psy-Q headers in include/psyq, without any of it being
decompiled - the calls resolve straight to the code already in the binary.

Anything we have named ourselves (LoadOverlay, g_overlay_dest, ...) rides along
in the same file.

Writes config/<game>/<target>.names.ld.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GAME = "p1-jp"
GHIDRA = os.path.join(ROOT, "config", GAME, "ghidra")

# target -> (ghidra json, address space)
SPACE = {
    "main": ("SLPS_005_00.json", "ram"),
    "atlus": ("ATLUS_EXE.json", "ram"),
    "open": ("OPEN_EXE.json", "ram"),
    "movie": ("MOVIE_EXE.json", "ram"),
    "end": ("END_EXE.json", "ram"),
    "dng": ("SLPS_005_00.json", "OVL_DNG"),
    "btlp": ("SLPS_005_00.json", "OVL_BTLP"),
    "s2d": ("SLPS_005_00.json", "OVL_S2D"),
    "adv": ("SLPS_005_00.json", "OVL_ADV"),
    "casino": ("SLPS_005_00.json", "OVL_CASINO"),
    "name": ("SLPS_005_00.json", "OVL_NAME"),
}

VALID = re.compile(r"^[A-Za-z_][A-Za-z_0-9]*$")


def gen(target):
    jf, space = SPACE[target]
    path = os.path.join(GHIDRA, jf)
    if not os.path.exists(path):
        print("  %-8s no Ghidra export (%s)" % (target, os.path.basename(path)))
        return
    doc = json.load(open(path))
    sp = doc["spaces"][space]
    blk = sp["blocks"][0]
    lo, hi = blk["start"], blk["end"]

    # An overlay calls into the resident main EXE, so it needs main's names too
    # (that is where the bulk of the Psy-Q SDK actually lives).
    spaces = [sp]
    if space.startswith("OVL_"):
        spaces.append(doc["spaces"]["ram"])

    def collect(entries, source, blo, bhi, clashes):
        for src in (source.get("names", {}), source.get("symbols", {})):
            for hexaddr, name in src.items():
                addr = int(hexaddr, 16)
                if not (blo <= addr <= bhi):
                    continue      # e.g. Ghidra's synthetic GTE macro space
                if not VALID.match(name):
                    continue      # skip anything not a C identifier
                if name.startswith(("FUN_", "thunk_FUN_")):
                    continue      # unnamed - the address form is used instead
                # One name can only mean one address. Two labels sharing a name
                # is a mistake in Ghidra, not something to resolve here - the
                # loser would vanish from the linker fragment and every source
                # using it would silently point at the wrong object.
                if entries.get(name, addr) != addr:
                    clashes.setdefault(name, set()).update(
                        (entries[name], addr))
                entries.setdefault(name, addr)

    # Function names first, then data/label names; a name already taken wins.
    # Symbols are accepted across every block of the space, not just the
    # initialized one - globals live in uninitialized RAM.
    entries = {}
    clashes = {}
    for source in spaces:
        ranges = source.get("sym_ranges")
        if not ranges:
            b = source["blocks"][0]
            ranges = [[b["start"], b["end"]]]
        for blo, bhi in ranges:
            collect(entries, source, blo, bhi, clashes)

    for name in sorted(clashes):
        where = sorted(clashes[name])
        shown = " ".join("0x%08X" % a for a in where[:4])
        if len(where) > 4:
            shown += " and %d more" % (len(where) - 4)
        print("  %-8s WARNING %s names %s - rename one in Ghidra"
              % (target, name, shown))

    out = os.path.join(ROOT, "config", GAME, "%s.names.ld" % target)
    with open(out, "w", newline="\n") as fh:
        fh.write("/* Generated by tools/gen_names.py from Ghidra analysis.\n")
        fh.write("   %s: space=%s vram=0x%08X-0x%08X */\n\n" % (target, space, lo, hi))
        for name in sorted(entries):
            fh.write("PROVIDE(%s = 0x%08X);\n" % (name, entries[name]))
    print("  %-8s %5d named symbols -> %s"
          % (target, len(entries), os.path.relpath(out, ROOT)))


if __name__ == "__main__":
    names = sys.argv[1:] or list(SPACE)
    print("generating symbol maps")
    for t in names:
        gen(t)
