"""Resolve dangling in-binary references left by large data runs.

spimdisasm emits a big data region as one symbol with no interior labels, so a
%hi/%lo reference into the middle of it becomes an undefined symbol such as
`D_$main_80055970`. The name encodes the address, so defining the symbol to that
address is exact by construction - the bytes are already emitted in place by the
enclosing run; only the reference needs an address.

Links each target repeatedly, harvesting undefined symbols until the link is
clean, and writes config/<game>/<target>.undefined_extra.txt.
"""
import os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GAME = "p1-jp"
LD = "mipsel-linux-gnu-ld"
TARGETS = ["main", "atlus", "open", "movie", "end",
           "dng", "btlp", "s2d", "adv", "casino", "name"]

UNDEF = re.compile(r"undefined reference to `([A-Za-z_][A-Za-z_0-9$]*)'")
ADDR = re.compile(r"([0-9A-Fa-f]{8})$")


def objs_for(target):
    out = []
    base = os.path.join(ROOT, "build", GAME, target)
    for dirpath, _, files in os.walk(base):
        for f in files:
            if f.endswith(".o"):
                out.append(os.path.join(dirpath, f))
    return sorted(out)


def resolve(target):
    cfg = os.path.join(ROOT, "config", GAME)
    extra = os.path.join(cfg, f"{target}.undefined_extra.txt")
    known = {}
    if os.path.exists(extra):
        for line in open(extra):
            m = re.match(r"([A-Za-z_][\w$]*) = 0x([0-9A-Fa-f]+);", line)
            if m:
                known[m.group(1)] = int(m.group(2), 16)

    # splat's linker script already pulls in each object by relative path, so
    # passing them on the command line as well links everything twice. Run from
    # ROOT so those relative paths resolve.
    if not objs_for(target):
        print(f"  {target:8} no objects built yet - run make first")
        return 0

    for _ in range(12):
        with open(extra, "w", newline="\n") as fh:
            fh.write("/* Generated by tools/gen_undefined.py */\n")
            for k in sorted(known):
                fh.write(f"{k} = 0x{known[k]:08X};\n")
        cmd = [LD, "--no-check-sections",
               "-T", os.path.join(cfg, f"{target}.undefined_syms_auto.txt"),
               "-T", os.path.join(cfg, f"{target}.undefined_funcs_auto.txt"),
               "-T", extra,
               "-T", os.path.join(cfg, f"{target}.ld"),
               "-o", os.path.join(ROOT, "build", GAME, f"{target}.elf")]
        r = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
        if r.returncode == 0:
            print(f"  {target:8} link clean ({len(known)} extra symbols)")
            return len(known)
        found = set(UNDEF.findall(r.stderr))
        new = {s for s in found if s not in known}
        if not new:
            print(f"  {target:8} STUCK: {sorted(found)[:3]}")
            print("   " + "\n   ".join(r.stderr.strip().splitlines()[:4]))
            return -1
        for s in new:
            m = ADDR.search(s)
            if not m:
                print(f"  {target:8} cannot derive address from {s!r}")
                return -1
            known[s] = int(m.group(1), 16)
    print(f"  {target:8} did not converge")
    return -1


if __name__ == "__main__":
    names = sys.argv[1:] or TARGETS
    print("resolving in-binary references")
    bad = 0
    for t in names:
        if resolve(t) < 0:
            bad = 1
    sys.exit(bad)
