"""Generate splat configs for every Persona 1 (JP) target.

PS-EXEs get their vram/size read out of the 0x800 header; overlays are raw
images that the game CdReads to a fixed base (see docs/p1-memory-map.md).
"""
import os, struct, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GAME = "p1-jp"
DATA = f"scratch/extracted/{GAME}"
OVL_BASE = 0x800643A0

# name, disc-relative path, kind, vram (None = read from PS-EXE header), entry
PSEXE = [
    ("main",  "SLPS_005.00",    None),
    ("atlus", "EXE/ATLUS.EXE",  None),
    ("open",  "EXE/OPEN.EXE",   None),
    ("movie", "EXE/MOVIE.EXE",  None),
    ("end",   "EXE/END.EXE",    None),
]
OVERLAYS = [
    ("dng",    "DNG.BIN",    4, 0x80064D2C),
    ("btlp",   "BTLP.BIN",   5, 0x8007F408),
    ("s2d",    "S2D.BIN",    6, 0x80089C04),
    ("adv",    "ADV.BIN",    7, 0x8007D9EC),
    ("casino", "CASINO.BIN", 8, 0x80065DAC),
    ("name",   "NAME.BIN",   9, 0x800643A4),
]


def psexe_header(path):
    with open(path, "rb") as f:
        h = f.read(0x800)
    assert h[:8] == b"PS-X EXE", f"{path}: not a PS-EXE"
    pc, gp, text_addr, text_size = struct.unpack_from("<IIII", h, 0x10)
    return {"pc": pc, "gp": gp, "vram": text_addr, "size": text_size}


HEAD = """\
# Generated by tools/gen_splat_configs.py -- edit the generator, not this file.
name: Megami Ibunroku Persona (JP) - {label}
sha1: {sha1}

options:
  platform: psx
  basename: {name}
  base_path: ../..
  target_path: {target}
  asm_path: asm/{game}/{name}
  src_path: src/{game}/{name}
  build_path: build/{game}/{name}
  ld_script_path: config/{game}/{name}.ld
  symbol_addrs_path: config/{game}/{name}.symbols.txt
  undefined_syms_auto_path: config/{game}/{name}.undefined_syms_auto.txt
  undefined_funcs_auto_path: config/{game}/{name}.undefined_funcs_auto.txt
  create_asm_dependencies: True
  disassemble_all: False
  find_file_boundaries: True
  compiler: GCC
  section_order: {section_order}
  subalign: {subalign}
  ld_align_section_vram_end: {align_end}
  ld_align_segment_vram_end: {align_end}
  ld_bss_is_noload: False
  symbol_name_format: $VRAM

segments:
"""


def write(path, text):
    with open(path, "w", newline="\n") as f:
        f.write(text)
    print(f"  {os.path.relpath(path, ROOT)}")


def sha1_of(path):
    import hashlib
    h = hashlib.sha1()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    outdir = os.path.join(ROOT, "config", GAME)
    os.makedirs(outdir, exist_ok=True)
    print("PS-EXE targets:")
    for name, rel, _ in PSEXE:
        target = f"{DATA}/{rel}"
        full = os.path.join(ROOT, target)
        hdr = psexe_header(full)
        size = os.path.getsize(full)
        body = HEAD.format(label=name, name=name, game=GAME, target=target,
                           sha1=sha1_of(full),
                           section_order='[".text", ".data", ".rodata", ".bss"]',
                           subalign=16, align_end="True")
        body += f"""\
  - name: header
    type: header
    start: 0x0
    vram: 0x{hdr['vram']:08X}

  - name: {name}
    type: code
    start: 0x800
    vram: 0x{hdr['vram']:08X}
    subsegments:
      - [0x800, asm, {name}]

  - [0x{size:X}]
"""
        write(os.path.join(outdir, f"{name}.yaml"), body)
        print(f"      vram=0x{hdr['vram']:08X} size=0x{hdr['size']:X} "
              f"pc=0x{hdr['pc']:08X} gp=0x{hdr['gp']:08X}")

    print("overlay targets (all load at 0x%08X):" % OVL_BASE)
    for name, rel, ovl_id, entry in OVERLAYS:
        target = f"{DATA}/{rel}"
        full = os.path.join(ROOT, target)
        size = os.path.getsize(full)
        # The overlay id dword lives at file offset 0, so .data must come
        # first; 16-byte subalign would pad between it and .text (and at EOF),
        # which is what made these come out 12-24 bytes too long.
        body = HEAD.format(label=f"{name} overlay", name=name, game=GAME,
                           target=target, sha1=sha1_of(full),
                           section_order='[".data", ".text", ".rodata", ".bss"]',
                           subalign=4, align_end="False")
        body += f"""\
  # overlay id {ovl_id}; entry 0x{entry:08X} (base + 0x{entry - OVL_BASE:X})
  - name: {name}
    type: code
    start: 0x0
    vram: 0x{OVL_BASE:08X}
    subsegments:
      - [0x0, data, {name}_id]   # u32 overlay_id - not code
      - [0x4, asm, {name}]

  - [0x{size:X}]
"""
        write(os.path.join(outdir, f"{name}.yaml"), body)
        print(f"      id={ovl_id} entry=0x{entry:08X} (+0x{entry - OVL_BASE:X}) size=0x{size:X}")


if __name__ == "__main__":
    main()
