"""Harvest 'SYM + 0xNN' references out of the split asm.

When a %hi/%lo pair points into the middle of a large data run, spimdisasm has
no symbol for that exact address and renders it as  D_8009FB00 + 0x28 . The C
source instead declares  D_8009FB28 , so the target object and the compiled
candidate disagree on symbol names and decomp-permuter (which compares object
files) can never converge.

The base does not have to carry a default name. Once part of a run is named,
spimdisasm blames that name instead and renders  str_adv_ev03_bgd + 0x1f0 , so
the base is resolved through the target's own names.ld as well as the
address-derived forms - otherwise naming one string in a run silently hides
every reference that follows it.

This scans the emitted asm for those offset forms, resolves each to an absolute
address, and writes config/<game>/<target>.refs.txt. tools/gen_symbols.py splits
its data runs at those addresses, so the next split gives every reference its
own symbol.

Run:  gen_refs -> gen_symbols -> splat split   (make split does this)
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GAME = "p1-jp"
TARGETS = ["main", "atlus", "open", "movie", "end",
           "dng", "btlp", "s2d", "adv", "casino", "name"]

# e.g.  %hi(D_8009FB00 + 0x28)   or   %lo(func_80078EE8+0x8c)
#
# Only the address-derived bases are resolved here. Widening this to every name
# in names.ld looks right and is not: the harvest reads the asm the last split
# produced, so a cut that changes how spimdisasm renders the words after it
# changes what the next harvest finds, and the fixed point does not settle.
# A reference into an object we have *named* is handled where it is stable -
# gen_symbols cuts at every named data address straight from the Ghidra export.
REF = re.compile(r"%(?:hi|lo)\(\s*(?:D|func|jtbl)_([0-9A-Fa-f]{8})\s*\+\s*(0x[0-9A-Fa-f]+)\s*\)")


def scan(target):
    path = os.path.join(ROOT, "asm", GAME, target, target + ".s")
    if not os.path.exists(path):
        print("  %-8s no split asm yet" % target)
        return
    addrs = set()
    with open(path) as fh:
        for line in fh:
            for base, off in REF.findall(line):
                a = int(base, 16) + int(off, 16)
                if a % 4 == 0:
                    addrs.add(a)
    # Accumulate. Once a cut exists the reference no longer reads as
    # `SYM + 0xNN`, so rewriting the file from a fresh scan would drop exactly
    # the addresses that are doing their job and the split would oscillate.
    out = os.path.join(ROOT, "config", GAME, "%s.refs.txt" % target)
    if os.path.exists(out):
        for line in open(out):
            m = re.search(r"=\s*0x([0-9A-Fa-f]{8})\s*;", line)
            if m:
                addrs.add(int(m.group(1), 16))
    with open(out, "w", newline="\n") as fh:
        fh.write("// Generated by tools/gen_refs.py from the split asm.\n")
        for a in sorted(addrs):
            fh.write("D_%08X = 0x%08X;\n" % (a, a))
    print("  %-8s %5d offset references -> %s"
          % (target, len(addrs), os.path.relpath(out, ROOT)))


if __name__ == "__main__":
    names = sys.argv[1:] or TARGETS
    print("harvesting offset references")
    for t in names:
        scan(t)
